import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { M3_BASELINE_SEED, M3_ROLES, m3SchemeFromSeed, m3SeedArgb, type M3Role } from './m3scheme';

// Google's published Material 3 baseline scheme (seed #6750A4), transcribed from the spec tables.
// The generator is checked AGAINST this rather than seeded from it: if a library upgrade or a tone
// change moves a role away from the documented scheme, that is a spec regression, not a detail.
const PUBLISHED: Record<'light' | 'dark', Record<M3Role, string>> = {
    light: {
        primary: '#6750a4', 'on-primary': '#ffffff', 'primary-container': '#eaddff', 'on-primary-container': '#21005d',
        secondary: '#625b71', 'secondary-container': '#e8def8', 'on-secondary-container': '#1d192b',
        tertiary: '#7d5260', error: '#b3261e',
        surface: '#fef7ff', 'surface-container-low': '#f7f2fa', 'surface-container': '#f3edf7', 'surface-container-high': '#ece6f0',
        'on-surface': '#1d1b20', 'on-surface-variant': '#49454f', outline: '#79747e', 'outline-variant': '#cac4d0', scrim: '#000000',
    },
    dark: {
        primary: '#d0bcff', 'on-primary': '#381e72', 'primary-container': '#4f378b', 'on-primary-container': '#eaddff',
        secondary: '#ccc2dc', 'secondary-container': '#4a4458', 'on-secondary-container': '#e8def8',
        tertiary: '#efb8c8', error: '#f2b8b5',
        surface: '#141218', 'surface-container-low': '#1d1b20', 'surface-container': '#211f26', 'surface-container-high': '#2b2930',
        'on-surface': '#e6e0e9', 'on-surface-variant': '#cac4d0', outline: '#938f99', 'outline-variant': '#49454f', scrim: '#000000',
    },
};

const channels = (hex: string): number[] => [1, 3, 5].map(index => parseInt(hex.substr(index, 2), 16));
const distance = (a: string, b: string): number => Math.max(...channels(a).map((value, index) => Math.abs(value - channels(b)[index])));

const luminance = (hex: string): number => {
    const [r, g, b] = channels(hex).map(part => { const value = part / 255; return value <= 0.03928 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4; });
    return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const ratio = (a: string, b: string): number => { const [high, low] = [luminance(a), luminance(b)].sort((x, y) => y - x); return (high + 0.05) / (low + 0.05); };

const SURFACES: M3Role[] = ['surface', 'surface-container', 'surface-container-low', 'surface-container-high'];
const TEXT_PAIRS: [M3Role, M3Role][] = [['on-primary', 'primary'], ['on-primary-container', 'primary-container'], ['on-secondary-container', 'secondary-container'],
    ...SURFACES.flatMap(surface => (['on-surface', 'on-surface-variant', 'primary', 'error'] as M3Role[]).map(role => [role, surface] as [M3Role, M3Role]))];

describe('material 3 scheme derivation', () => {
    it('rejects anything that is not a hex color', () => {
        expect(m3SeedArgb('#6750a4')).toBe(m3SeedArgb('#6750A4'));
        expect(m3SeedArgb('#abc')).toBe(m3SeedArgb('#aabbcc'));
        ['', 'rebeccapurple', 'rgb(1,2,3)', '#12345', 'linear-gradient(red, blue)'].forEach(bad => expect(m3SeedArgb(bad)).toBeUndefined());
        expect(m3SchemeFromSeed('rebeccapurple')).toBeUndefined();
    });

    // ±1/255 is the rounding drift between the published table and the palette math that produced
    // it. `error` is the one substantive gap: the published baseline still carries the pre-2023
    // #b3261e, while M3's current error palette (hue 25 / chroma 84) gives #ba1a1a.
    it('reproduces the published baseline scheme from the baseline seed', () => {
        const scheme = m3SchemeFromSeed(M3_BASELINE_SEED)!;
        const offenders = (['light', 'dark'] as const).flatMap(variant => M3_ROLES
            .filter(role => role !== 'error')
            .filter(role => distance(scheme[variant][role], PUBLISHED[variant][role]) > 1)
            // The neutral palette carries a slightly different chroma than the one the published
            // surface tints were generated with; 6/255 on a near-white is not a visible difference.
            .filter(role => !(role.startsWith('surface') && distance(scheme[variant][role], PUBLISHED[variant][role]) <= 6))
            .map(role => `${variant} ${role}: ${scheme[variant][role]} vs published ${PUBLISHED[variant][role]}`));
        expect(offenders).toEqual([]);
        expect(scheme.light.primary).toBe(M3_BASELINE_SEED); // tone 40 of a palette seeded at tone 40
    });

    // The CSS baseline is generated by this same function, so "no seed" and "seed = the M3 baseline
    // color" must be the same widget. Anything else is a difference no user could explain.
    it('matches the baseline compiled into material3-tokens.css', () => {
        const css = readFileSync('src-widgets-ts/src/material3-tokens.css', 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');
        const [, lightBlock, darkBlock] = css.split('.materialdesign-widget.mdw-style-material3');
        const compiled = (block: string): Record<string, string> => Object.fromEntries(
            [...block.matchAll(/--md-sys-color-([a-z-]+):\s*var\(--mdw-seed-[a-z-]+,\s*(#[0-9a-f]{6})\)/g)].map(match => [match[1], match[2]]));
        const scheme = m3SchemeFromSeed(M3_BASELINE_SEED)!;
        expect(compiled(lightBlock)).toEqual(scheme.light);
        expect(compiled(darkBlock)).toEqual(scheme.dark);
    });

    // WCAG 1.4.3 / 1.4.11 for EVERY reachable scheme, not just the shipped baseline. Before Phase 9
    // an admin could seed a light primary and drop filled buttons to ~1.1:1; the tone map makes that
    // unreachable by construction, and this is what says so. Greys and the two extremes are in the
    // list because a fully desaturated seed has no meaningful hue and used to be the awkward case.
    it.each(['#6750a4', '#ffee00', '#00695c', '#b3261e', '#003366', '#888888', '#ffffff', '#000000'])('keeps every pair legible for seed %s', seed => {
        const scheme = m3SchemeFromSeed(seed)!;
        (['light', 'dark'] as const).forEach(variant => {
            expect(TEXT_PAIRS.filter(([front, back]) => ratio(scheme[variant][front], scheme[variant][back]) < 4.5)
                .map(([front, back]) => `${variant} ${front} on ${back}`)).toEqual([]);
            SURFACES.forEach(surface => expect(ratio(scheme[variant].outline, scheme[variant][surface])).toBeGreaterThanOrEqual(3));
        });
    });

    it('derives light and dark from one seed instead of taking two', () => {
        const scheme = m3SchemeFromSeed('#00695c')!;
        // Same palette, opposite ends of it: light takes the darker tone, dark the lighter one.
        expect(luminance(scheme.dark.primary)).toBeGreaterThan(luminance(scheme.light.primary));
        expect(luminance(scheme.dark.surface)).toBeLessThan(luminance(scheme.light.surface));
        // Error is fixed by the spec, so a red-seeded project still has a distinguishable error role.
        expect(m3SchemeFromSeed('#b3261e')!.light.error).toBe(scheme.light.error);
    });
});
