import React from 'react';
import type { RxWidgetInfo, VisRxWidgetState } from '@iobroker/types-vis-2';
import { renderIcon } from './MaterialDesignButtons';
import { RenderProps, VisWidget, createInfo, setStateValue, stateValue } from './widgetUtils';

type Item = { menuId?: string; text?: string; header?: string; divider?: boolean; icon?: string; iconColor?: string; subMenuIconColor?: string; setValueOnMenuToggleClick?: boolean; subMenus?: Item[]; empty?: boolean };
type Data = Record<string, unknown> & { oid?: string; navItemCount?: number; drawerItemsDataMethod?: string; drawerItemsJsonString?: string };
const s = (v: unknown, d = ''): string => v === undefined || v === null || v === '' || v === 'null' ? d : String(v);
const n = (v: unknown, d = 0): number => v === undefined || v === null || v === '' || !Number.isFinite(Number(v)) ? d : Number(v);
const b = (v: unknown, d = false): boolean => v === undefined || v === null || v === '' ? d : v === true || v === 'true' || v === 1 || v === '1';
const px = (v: unknown): string | undefined => { const text = s(v); return text ? (Number.isFinite(Number(text)) ? `${text}px` : text) : undefined; };
function parse(v: unknown): Item[] { try { const result: unknown = JSON.parse(s(v)); return Array.isArray(result) ? result as Item[] : [{ text: 'Error in JSON string', icon: 'alert', iconColor: 'red' }]; } catch { return [{ text: 'Error in JSON string', icon: 'alert', iconColor: 'red' }]; } }
function items(data: Data): Item[] { if (s(data.drawerItemsDataMethod, 'inputPerEditor') === 'jsonStringObject') return parse(data.drawerItemsJsonString); return Array.from({ length: Math.max(1, Math.floor(n(data.navItemCount, 1)) + 1) }, (_, i) => { let subMenus: Item[] | undefined; if (s(data[`submenus${i}`])) subMenus = parse(data[`submenus${i}`]); const empty = !s(data[`labels${i}`]) && !s(data[`iconDrawer${i}`]) && !s(data[`headers${i}`]) && !s(data[`menuId${i}`]) && !(subMenus && subMenus.length); return { menuId: s(data[`menuId${i}`]), text: s(data[`labels${i}`], 'Menu Item'), header: s(data[`headers${i}`]), divider: b(data[`dividers${i}`]), icon: s(data[`iconDrawer${i}`]), iconColor: s(data[`iconDrawerColor${i}`], s(data.iconDrawerColor, '#44739e')), subMenuIconColor: s(data[`subIconDrawerColor${i}`], s(data.subIconDrawerColor, '#44739e')), setValueOnMenuToggleClick: b(data[`setValueOnMenuToggleClick${i}`]), subMenus, empty }; }); }
const attrs: RxWidgetInfo['visAttrs'] = [
    { name: 'common', fields: [{ name: 'oid', label: 'oid', type: 'id' }, { name: 'showIndexNum', label: 'showIndexNum', type: 'checkbox' }, { name: 'navItemCount', label: 'navItemCount', type: 'number', default: 1 }, { name: 'navDefaultValue', label: 'navDefaultValue', type: 'number', default: 0 }, { name: 'navDisableDefaultValue', label: 'navDisableDefaultValue', type: 'checkbox' }, { name: 'selectedItemName_oid', label: 'selectedItemName_oid', type: 'id' }, { name: 'debug', label: 'debug', type: 'checkbox' }] },
    { name: 'topAppBarLayout', label: 'group_topAppBarLayout', fields: [{ name: 'topAppBarLayout', label: 'topAppBarLayout', type: 'select', options: ['standard', 'dense', 'short'], default: 'standard' }, { name: 'titleTopAppBar', label: 'titleTopAppBar', type: 'html', default: 'Material Design Widgets' }, { name: 'colorTopAppBarTitle', label: 'colorTopAppBarTitle', type: 'color' }, { name: 'colorTopAppBarBackground', label: 'colorTopAppBarBackground', type: 'color' }, { name: 'titleFont', label: 'titleFont', type: 'fontname' }, { name: 'titleFontSize', label: 'titleFontSize', type: 'number' }, { name: 'topAppBarIconColor', label: 'topAppBarIconColor', type: 'color' }, { name: 'showSelectedItemAsTitle', label: 'showSelectedItemAsTitle', type: 'checkbox', default: true }, { name: 'showSelectedItemIconInTitle', label: 'showSelectedItemIconInTitle', type: 'checkbox', default: true }, { name: 'iconTitleHeight', label: 'iconTitleHeight', type: 'dimension' }, { name: 'topAppBarZ_index', label: 'topAppBarZ_index', type: 'number', default: 998 }, { name: 'vibrateTopAppBarOnMobilDevices', label: 'vibrateTopAppBarOnMobilDevices', type: 'number', default: 50 }] },
    { name: 'drawerLayout', label: 'group_drawerLayout', fields: [{ name: 'drawerLayout', label: 'drawerLayout', type: 'select', options: ['modal', 'permanent', 'auto'], default: 'modal' }, { name: 'permanentIfResolutionHigherThan', label: 'permanentIfResolutionHigherThan', type: 'number', default: 800 }, { name: 'drawerItemLayout', label: 'drawerItemLayout', type: 'select', options: ['standard', 'backdrop'], default: 'standard' }, { name: 'listItemDividerStyle', label: 'listItemDividerStyle', type: 'select', options: ['standard', 'padded', 'inset'], default: 'standard' }, { name: 'drawerWidth', label: 'drawerWidth', type: 'number' }, { name: 'z_index', label: 'z_index', type: 'number', default: 1000 }, { name: 'showHeader', label: 'showHeader', type: 'checkbox', default: true }, { name: 'headerLabel', label: 'headerLabel', type: 'html' }, { name: 'showLabels', label: 'showLabels', type: 'checkbox', default: true }, { name: 'drawerIconHeight', label: 'drawerIconHeight', type: 'number' }, { name: 'listItemAlignment', label: 'listItemAlignment', type: 'select', options: ['left', 'center', 'right'], default: 'left' }, { name: 'listItemTextFont', label: 'listItemTextFont', type: 'fontname' }, { name: 'listItemTextSize', label: 'listItemTextSize', type: 'text' }, { name: 'backdropLabelBackgroundHeight', label: 'backdropLabelBackgroundHeight', type: 'slider', min: 0, max: 100, step: 1, default: 30 }, { name: 'vibrateDrawerOnMobilDevices', label: 'vibrateDrawerOnMobilDevices', type: 'number' }] },
    { name: 'drawerColors', label: 'group_drawerColors', fields: ['colorDrawerBackground', 'colorDrawerItemBackground', 'colorDrawerHeaderBackground', 'iconDrawerColor', 'iconDrawerColorSelected', 'subIconDrawerColor', 'subIconDrawerColorSelected', 'colorListItemHover', 'colorListItemSelected', 'colorListItemText', 'colorListItemTextSelected', 'colorListItemTextDisabled', 'colorListItemIconDisabled', 'colorListItemHeaders', 'colorListItemDivider', 'colorSubItemToggleIcon', 'colorDrawerbackdropLabelBackground', 'colorDrawerbackdropLabelBackgroundActive'].map(name => ({ name, label: name, type: 'color' as const })) },
    { name: 'drawerSubItemsLayout', label: 'group_drawerSubItemsLayout', fields: [{ name: 'drawerSubItemLayout', label: 'drawerSubItemLayout', type: 'select', options: ['standard', 'backdrop'], default: 'standard' }, { name: 'listSubItemDividerStyle', label: 'listSubItemDividerStyle', type: 'select', options: ['standard', 'padded', 'inset'], default: 'standard' }, { name: 'colorListSubItemDivider', label: 'colorListSubItemDivider', type: 'color' }, { name: 'drawerSubItemIconHeight', label: 'drawerSubItemIconHeight', type: 'number' }, { name: 'listSubItemAlignment', label: 'listSubItemAlignment', type: 'select', options: ['left', 'center', 'right'], default: 'left' }, { name: 'listItemSubTextFont', label: 'listItemSubTextFont', type: 'fontname' }, { name: 'listSubItemTextSize', label: 'listSubItemTextSize', type: 'text' }, { name: 'showSubItemsLabels', label: 'showSubItemsLabels', type: 'checkbox', default: true }, { name: 'backdropSubLabelBackgroundHeight', label: 'backdropSubLabelBackgroundHeight', type: 'slider', min: 0, max: 100, step: 1 }] },
    { name: 'drawerSubItemsColors', label: 'group_drawerSubItemsColors', fields: ['colorDrawerSubBackground', 'colorDrawerSubItemBackground', 'colorListSubItemHover', 'colorListSubItemSelected', 'colorListSubItemText', 'colorListSubItemTextSelected', 'colorDrawerbackdropSubLabelBackground', 'colorDrawerbackdropSubLabelBackgroundActive'].map(name => ({ name, label: name, type: 'color' as const })) },
    { name: 'drawerItemsData', label: 'group_drawerItemsData', fields: [{ name: 'drawerItemsDataMethod', label: 'drawerItemsDataMethod', type: 'select', options: ['inputPerEditor', 'jsonStringObject'], default: 'inputPerEditor' }, { name: 'drawerItemsJsonString', label: 'drawerItemsJsonString', type: 'html' }] },
    { name: 'drawerItems', label: 'group_drawerItems', indexFrom: 0, indexTo: 'navItemCount', hidden: (data: Data) => s(data.drawerItemsDataMethod, 'inputPerEditor') !== 'inputPerEditor', fields: [{ name: 'menuId', label: 'menuId', type: 'text' }, { name: 'labels', label: 'labels', type: 'html' }, { name: 'headers', label: 'headers', type: 'html' }, { name: 'dividers', label: 'dividers', type: 'checkbox' }, { name: 'iconDrawer', label: 'iconDrawer', type: 'icon' }, { name: 'iconDrawerColor', label: 'iconDrawerColor', type: 'color' }, { name: 'subIconDrawerColor', label: 'subIconDrawerColor', type: 'color' }, { name: 'setValueOnMenuToggleClick', label: 'setValueOnMenuToggleClick', type: 'checkbox' }, { name: 'submenus', label: 'submenus', type: 'html' }, { name: 'permissionGroupSelector', label: 'permissionGroupSelector', type: 'text' }, { name: 'permissionVisibility', label: 'permissionVisibility', type: 'select', options: ['hide', 'disabled'], default: 'hide' }] },
];
export default class MaterialDesignTopAppBar extends VisWidget {
    private open = false; private expanded = new Set<number>();
    static getWidgetInfo(): RxWidgetInfo { return { ...createInfo('tplVis2-materialdesign-TopAppBar-Navigation', 'Top App Bar', attrs), visPrev: '<img src="widgets/materialdesign/img/prev_top_app_bar_nav_drawer.png"></img>', visDefaultStyle: { width: 400, height: 270 } }; }
    getWidgetInfo(): RxWidgetInfo { return MaterialDesignTopAppBar.getWidgetInfo(); }
    renderWidgetBody(props: RenderProps): React.JSX.Element {
        super.renderWidgetBody(props); const data = this.state.rxData as unknown as Data; const list = items(data); const current = stateValue(this.state as VisRxWidgetState, s(data.oid)); const selected = current === undefined && !b(data.navDisableDefaultValue) ? n(data.navDefaultValue) : n(current); const permanent = s(data.drawerLayout) === 'permanent' || (s(data.drawerLayout) === 'auto' && typeof window !== 'undefined' && window.innerWidth >= n(data.permanentIfResolutionHigherThan, 800)); const visible = permanent || this.open; const flat: Array<{ item: Item; index: number; parent?: Item }> = []; let index = 0; list.forEach(item => { flat.push({ item, index: index++ }); item.subMenus?.forEach(sub => flat.push({ item: sub, index: index++, parent: item })); }); const chosen = flat.find(entry => entry.index === selected); const title = b(data.showSelectedItemAsTitle, true) && chosen ? chosen.item.text : s(data.titleTopAppBar, 'Material Design Widgets'); const select = (entry: { item: Item; index: number; parent?: Item }): void => { if (entry.item.subMenus?.length) { if (this.expanded.has(entry.index)) this.expanded.delete(entry.index); else this.expanded.add(entry.index); if (entry.item.setValueOnMenuToggleClick) setStateValue(this.props, s(data.oid), entry.index); this.forceUpdate(); return; } setStateValue(this.props, s(data.oid), entry.index); if (s(data.selectedItemName_oid)) setStateValue(this.props, s(data.selectedItemName_oid), entry.parent ? `${s(entry.parent.menuId, entry.parent.text)}.${s(entry.item.menuId, entry.item.text)}` : s(entry.item.menuId, entry.item.text)); if (!permanent) { this.open = false; this.forceUpdate(); } window.scrollTo?.({ top: 0, left: 0 }); };
        const itemNode = (entry: { item: Item; index: number; parent?: Item }): React.JSX.Element => <button key={entry.index} className={`mdc-list-item${entry.index === selected ? ' mdc-list-item--activated' : ''}${entry.parent ? ' isSubItem' : ''}`} onClick={() => select(entry)} style={{ alignItems: 'center', background: entry.index === selected ? s(entry.parent ? data.colorListSubItemSelected : data.colorListItemSelected) : s(entry.parent ? data.colorDrawerSubItemBackground : data.colorDrawerItemBackground), border: 0, borderBottom: entry.item.divider ? `1px solid ${s(entry.parent ? data.colorListSubItemDivider : data.colorListItemDivider)}` : undefined, color: entry.index === selected ? s(entry.parent ? data.colorListSubItemTextSelected : data.colorListItemTextSelected) : s(entry.parent ? data.colorListSubItemText : data.colorListItemText), cursor: 'pointer', display: 'flex', fontFamily: s(entry.parent ? data.listItemSubTextFont : data.listItemTextFont), fontSize: px(entry.parent ? data.listSubItemTextSize : data.listItemTextSize), justifyContent: entry.parent ? s(data.listSubItemAlignment, 'left') : s(data.listItemAlignment, 'left'), minHeight: 48, padding: '0 16px', textAlign: 'left', width: '100%' }}>{renderIcon(s(entry.item.icon), s(entry.item.iconColor, entry.parent ? s(data.subIconDrawerColor) : s(data.iconDrawerColor)), n(entry.parent ? data.drawerSubItemIconHeight : data.drawerIconHeight, 24), true)}{(entry.parent ? b(data.showSubItemsLabels, true) : b(data.showLabels, true)) ? <span className="mdc-list-item__text" style={{ flex: 1, marginLeft: 16 }} dangerouslySetInnerHTML={{ __html: `${b(data.showIndexNum) ? `[${entry.index}] ` : ''}${s(entry.item.text, entry.parent ? 'Menu SubItem' : 'Menu Item')}` }} /> : null}{entry.item.subMenus?.length ? renderIcon(this.expanded.has(entry.index) ? 'menu-up' : 'menu-down', s(data.colorSubItemToggleIcon, '#44739e'), 20, true) : null}</button>;
        return <div className="materialdesign-widget materialdesign-topAppBar-with-Drawer" style={{ height: '100%', overflow: 'hidden', position: 'relative', width: '100%' }}><header className={`mdc-top-app-bar mdc-top-app-bar--${s(data.topAppBarLayout, 'standard')}`} style={{ alignItems: 'center', background: s(data.colorTopAppBarBackground, '#44739e'), color: s(data.colorTopAppBarTitle, '#fff'), display: 'flex', fontFamily: s(data.titleFont), fontSize: n(data.titleFontSize, 20), height: s(data.topAppBarLayout) === 'dense' ? 48 : 64, padding: '0 12px', position: 'relative', zIndex: n(data.topAppBarZ_index, 998) }}><button onClick={() => { this.open = !this.open; this.forceUpdate(); if (n(data.vibrateTopAppBarOnMobilDevices) > 0) navigator.vibrate?.(n(data.vibrateTopAppBarOnMobilDevices)); }} style={{ background: 'transparent', border: 0, color: s(data.topAppBarIconColor, 'currentColor') }}>{renderIcon('menu', s(data.topAppBarIconColor, 'currentColor'), 24, true)}</button><span className="mdc-top-app-bar__title" style={{ alignItems: 'center', display: 'flex' }}>{b(data.showSelectedItemIconInTitle, true) && chosen?.item.icon ? renderIcon(chosen.item.icon, chosen.item.iconColor, n(data.iconTitleHeight, 30), true) : null}<span dangerouslySetInnerHTML={{ __html: s(title) }} /></span></header>{visible ? <><aside className={`mdc-drawer${permanent ? ' mdc-drawer--dismissible mdc-drawer--open' : ' mdc-drawer--modal mdc-drawer--open'}`} style={{ background: s(data.colorDrawerBackground, '#fff'), height: `calc(100% - ${s(data.topAppBarLayout) === 'dense' ? 48 : 64}px)`, left: 0, overflowY: 'auto', position: 'absolute', top: s(data.topAppBarLayout) === 'dense' ? 48 : 64, width: n(data.drawerWidth, 256), zIndex: n(data.z_index, 1000) }}>{b(data.showHeader, true) ? <div className="mdc-drawer__header" style={{ background: s(data.colorDrawerHeaderBackground), padding: 16 }} dangerouslySetInnerHTML={{ __html: s(data.headerLabel) }} /> : null}<nav className="mdc-list">{list.flatMap((item, root) => { const rootEntry = flat.find(entry => entry.item === item)!; if (item.empty) { return []; } const children = item.subMenus && this.expanded.has(rootEntry.index) ? flat.filter(entry => entry.parent === item).map(itemNode) : []; return [item.header ? <div className="mdc-list-group__subheader" key={`header${root}`} style={{ color: s(data.colorListItemHeaders), padding: '12px 16px' }} dangerouslySetInnerHTML={{ __html: item.header }} /> : null, itemNode(rootEntry), ...children]; })}</nav></aside>{!permanent ? <div className="mdc-drawer-scrim" onClick={() => { this.open = false; this.forceUpdate(); }} style={{ background: 'rgba(0,0,0,.32)', inset: 0, position: 'absolute', zIndex: n(data.z_index, 1000) - 1 }} /> : null}</> : null}</div>;
    }
}
