import React from 'react';
import '@fontsource/jura/files/jura-latin-400-normal.woff2';
import '@fontsource/roboto-condensed/files/roboto-condensed-latin-400-normal.woff2';

import type { RxRenderWidgetProps, RxWidgetInfo, RxWidgetInfoAttributesField, VisRxWidgetProps, VisRxWidgetState } from '@iobroker/types-vis-2';
import { IconFilePicker, type PickerSocket, type PickerTexts, type PickerTheme } from './IconFilePicker';
import type VisRxWidget from '@iobroker/types-vis-2/visRxWidget';
import colors from '../../admin/lib/colors.json';
import fonts from '../../admin/lib/fonts.json';
import fontSizes from '../../admin/lib/fontSizes.json';
// Runtime needs ONLY the `group_*` attribute-group headers (bridged below into the legacy
// systemDictionary). Importing the full `./translations` dictionary here would drag its ~500 kB
// chunk into every widget at runtime; that dictionary is reserved for the editor's `./translations`
// module-federation expose. This tiny subset is generated by scripts/gen-group-labels.cjs.
import groupLabels from './generated/groupLabels.json';
import '../../fonts.css';
// Material Design Icons webfont, vendored from npm (@mdi/font 6.7.96 — the exact legacy
// version). `mdi-font.css` carries the `.mdi` / `.mdi-<name>` glyph classes + a
// woff2-ONLY "Material Design Icons" @font-face (generated from the package's min.css;
// the eot/woff/ttf formats it also ships are dead weight for our chrome89 target). So the
// VIS2 bundle supplies the icon font itself, no longer depending on legacy CSS.
import './mdi-font.css';
// MDC baseline rules (typography + card elevation/media aspect-ratio) that a few widgets
// use ambiently and cannot express inline. Vendored from the legacy bundle so the widgets
// keep rendering after the VIS1 legacy CSS is removed. See the file header for scope.
import './materialdesign-mdc.css';
import './vis2-editor-dialog.css';

// VIS 2 resolves widget-attribute GROUP headers via the legacy `window.vis._` / `window.systemDictionary`,
// which the component i18n does NOT populate — so custom groups (e.g. `group_theme`) render as raw keys.
// Bridge our `group_*` labels into that legacy dictionary once on load.
(function registerGroupLabels(): void {
    const win = window as unknown as { systemDictionary?: Record<string, Record<string, string>> };
    const sd = (win.systemDictionary ||= {});
    (Object.keys(groupLabels) as Array<keyof typeof groupLabels>).forEach(lang => {
        const words = groupLabels[lang] as Record<string, string>;
        Object.keys(words).forEach(key => {
            (sd[key] ||= {})[lang as string] = words[key];
        });
    });
})();

export interface BaseRxData {
    oid: string;
    label: string;
    prefix: string;
    suffix: string;
    color: string;
    size: string;
    icon: string;
    value: string;
}

export interface PressState {
    active?: boolean;
    hovered?: boolean;
}

export const setColor = '#ffc107';

export const commonAttrs = [
    {
        name: 'common',
        label: 'group_common',
        fields: [
            {
                name: 'oid',
                label: 'oid',
                type: 'id',
            },
            {
                name: 'label',
                label: 'label',
                type: 'text',
                default: '',
            },
        ],
    },
];

export const valueTextAttrs = [
    ...commonAttrs,
    {
        name: 'text',
        fields: [
            {
                name: 'prefix',
                label: 'prefix',
                type: 'text',
                default: '',
            },
            {
                name: 'suffix',
                label: 'suffix',
                type: 'text',
                default: '',
            },
        ],
    },
];

export function stateValue(state: VisRxWidgetState, oid: string): ioBroker.StateValue | undefined {
    return oid ? state.values?.[`${oid}.val`] : undefined;
}

// The vis/ioBroker system language (like the legacy widgets used), falling back to the browser locale.
export function visLocale(): string | undefined {
    if (typeof window === 'undefined') return undefined;
    const win = window as unknown as { vis?: { language?: string }; systemLang?: string };
    return win.vis?.language || win.systemLang || window.navigator.language;
}

// Native replacement for moment's date tokens (VIS1 custom-format fields used moment).
// Longer tokens must precede shorter ones in the alternation so YYYY beats YY, MMMM beats MM, etc.
export function formatMoment(date: Date, token: string, locale?: string): string {
    if (!token) return '';
    const pad = (value: number): string => String(value).padStart(2, '0');
    const hours12 = date.getHours() % 12 || 12;
    const map: Record<string, () => string> = {
        YYYY: () => String(date.getFullYear()),
        YY: () => String(date.getFullYear()).slice(-2),
        MMMM: () => new Intl.DateTimeFormat(locale, { month: 'long' }).format(date),
        MMM: () => new Intl.DateTimeFormat(locale, { month: 'short' }).format(date).replace('.', ''),
        MM: () => pad(date.getMonth() + 1),
        M: () => String(date.getMonth() + 1),
        DD: () => pad(date.getDate()),
        D: () => String(date.getDate()),
        dddd: () => new Intl.DateTimeFormat(locale, { weekday: 'long' }).format(date),
        ddd: () => new Intl.DateTimeFormat(locale, { weekday: 'short' }).format(date).replace('.', ''),
        dd: () => new Intl.DateTimeFormat(locale, { weekday: 'narrow' }).format(date),
        HH: () => pad(date.getHours()),
        H: () => String(date.getHours()),
        hh: () => pad(hours12),
        h: () => String(hours12),
        mm: () => pad(date.getMinutes()),
        m: () => String(date.getMinutes()),
        ss: () => pad(date.getSeconds()),
        s: () => String(date.getSeconds()),
        A: () => (date.getHours() < 12 ? 'AM' : 'PM'),
        a: () => (date.getHours() < 12 ? 'am' : 'pm'),
    };
    return token.replace(/YYYY|YY|MMMM|MMM|MM|M|dddd|ddd|dd|DD|D|HH|H|hh|h|mm|m|ss|s|A|a/g, match => (map[match] ? map[match]() : match));
}

// Native replacement for moment-duration-format tokens. The largest unit present accumulates the
// overflow (moment-duration-format's default), because higher units skipped in the loop leave their
// seconds in `remainder`. Doubled tokens (hh, mm, …) zero-pad; single tokens don't.
export function formatDurationTokens(totalSeconds: number, template: string): string {
    const units: Array<[string, number]> = [['d', 86400], ['h', 3600], ['m', 60], ['s', 1]];
    if (!units.some(([letter]) => template.includes(letter))) return String(totalSeconds);
    const sign = totalSeconds < 0 ? '-' : '';
    let remainder = Math.abs(Math.floor(totalSeconds));
    const values: Record<string, number> = {};
    for (const [letter, per] of units) {
        if (!template.includes(letter)) continue;
        values[letter] = Math.floor(remainder / per);
        remainder %= per;
    }
    return sign + template.replace(/dd|hh|mm|ss|d|h|m|s/g, token => {
        const value = values[token[0]];
        if (value === undefined) return token;
        return token.length === 2 ? String(value).padStart(2, '0') : String(value);
    });
}

// Native replacement for moment's duration().humanize(): the single largest applicable unit,
// localized via Intl unit formatting (e.g. "2 hours" / "2 Stunden").
export function humanizeDuration(totalSeconds: number, locale?: string): string {
    const abs = Math.abs(totalSeconds);
    const table: Array<[Intl.NumberFormatOptions['unit'], number]> = [
        ['year', 31536000], ['month', 2592000], ['week', 604800], ['day', 86400],
        ['hour', 3600], ['minute', 60], ['second', 1],
    ];
    let unit: Intl.NumberFormatOptions['unit'] = 'second';
    let value = Math.round(abs);
    for (const [candidate, per] of table) {
        if (abs >= per) { unit = candidate; value = Math.round(abs / per); break; }
    }
    try {
        return new Intl.NumberFormat(locale, { style: 'unit', unit, unitDisplay: 'long' }).format(value);
    } catch {
        return `${value} ${unit}${value === 1 ? '' : 's'}`;
    }
}

// CSS font-size that survives a theme `var(--…)` (or any string with a unit): return it as-is, otherwise numeric → `${n}px`.
export function sizeCss(value: unknown, fallbackPx: number): string {
    if (typeof value === 'string') {
        const text = value.trim();
        if (text.startsWith('var(') || /[a-z%)]$/i.test(text)) return text;
    }
    const num = value === '' || value === null || value === undefined ? NaN : Number(value);
    return `${Number.isFinite(num) ? num : fallbackPx}px`;
}

export function setStateValue(props: VisRxWidgetProps, oid: string, value: ioBroker.StateValue): void {
    const context = (props as unknown as { context?: { setValue?: (id: string, value: ioBroker.StateValue) => void } }).context;
    if (oid && context?.setValue) {
        context.setValue(oid, value);
    }
}

export function parseActionValue(value: string): ioBroker.StateValue {
    if (value === 'true') {
        return true;
    }
    if (value === 'false') {
        return false;
    }
    if (value !== '' && !Number.isNaN(Number(value))) {
        return Number(value);
    }
    return value;
}

export function card(children: React.ReactNode): React.JSX.Element {
    return <div style={{ boxSizing: 'border-box', width: '100%', height: '100%', padding: 8 }}>{children}</div>;
}

// Uniform editor-palette preview: a small square white chip with a single MDI
// glyph (slate). Self-contained (own @font-face) so it renders in the palette
// without the widget's runtime CSS. `glyph` is an MDI codepoint, e.g. 'F00ED'.
export function squarePreview(glyph: string): string {
    return (
        '<style>@font-face{font-family:"Material Design Icons";src:url("widgets/vis2-materialdesign/img/materialdesignicons-webfont.woff2") format("woff2");}' +
        '.mdw-prev-icon{font-family:"Material Design Icons";font-weight:normal;font-style:normal;line-height:1;display:inline-block;}</style>' +
        '<div style="width:100%;height:100%;display:flex;align-items:center;justify-content:center;box-sizing:border-box;padding:0;">' +
        '<div style="width:100%;max-width:44px;aspect-ratio:1;border-radius:8px;background:#fff;display:flex;align-items:center;justify-content:center;box-shadow:inset 0 0 0 1px rgba(0,0,0,.08);box-sizing:border-box;">' +
        `<span class="mdw-prev-icon" style="font-size:22px;color:#44739e;">&#x${glyph};</span></div></div>`
    );
}

export function createInfo(id: string, name: string, attrs: RxWidgetInfo['visAttrs']): RxWidgetInfo {
    return {
        id,
        visSet: 'vis2-materialdesign',
        visSetLabel: 'Material Design',
        visSetColor: setColor,
        visName: name,
        visAttrs: [
            {
                name: 'theme',
                fields: themeFields(name),
            },
            ...attrs,
        ],
    };
}

// Combined icon+file picker as a `type:'custom'` field (replaces plain `type:'icon'`): lets the
// user pick an MDI font icon OR browse an ioBroker file, both stored in the same data key. In counted
// groups VIS2 normally suffixes `field.name` with the row index (e.g. `listImage0`). Older editor
// builds may instead keep the base name and expose the row as `field.index`; support both shapes.
export function iconFieldDataKey(name: string, field: { name?: string; index?: number }): string {
    const fieldName = field.name ?? name;
    return field.index === undefined || fieldName !== name ? fieldName : `${fieldName}${field.index}`;
}

export function iconField(name: string, label: string, def?: string): RxWidgetInfoAttributesField {
    return {
        type: 'custom',
        name,
        label,
        default: def,
        component: (field, data, onDataChange, props) => {
            const pickerTexts: PickerTexts = {
                adapter: VisWidget.t('iconPickerAdapter'),
                cancel: VisWidget.t('iconPickerCancel'),
                choose: VisWidget.t('iconPickerChoose'),
                chooseEllipsis: VisWidget.t('iconPickerChooseEllipsis'),
                clear: VisWidget.t('iconPickerClear'),
                empty: VisWidget.t('iconPickerEmpty'),
                file: VisWidget.t('iconPickerFile'),
                icon: VisWidget.t('iconPickerIcon'),
                loading: VisWidget.t('iconPickerLoading'),
                preview: VisWidget.t('iconPickerPreview'),
                search: VisWidget.t('iconPickerSearch'),
                up: VisWidget.t('iconPickerUp'),
            };
            const indexedField = field as { name?: string; index?: number };
            const key = iconFieldDataKey(name, indexedField);
            const rec = data as Record<string, unknown>;
            const ctx = (props as { context?: { socket?: PickerSocket; theme?: PickerTheme } })?.context;
            return (
                <IconFilePicker
                    label={VisWidget.t(label)}
                    onChange={value => onDataChange({ [key]: value })}
                    socket={ctx?.socket}
                    texts={pickerTexts}
                    theme={ctx?.theme}
                    value={String(rec[key] ?? '')}
                />
            );
        },
    } as RxWidgetInfoAttributesField;
}

type ThemeEntry = { id: string; desc: string; widget: string };
type ThemeType = 'colors' | 'fonts' | 'fontSizes';

const themeLists: Record<ThemeType, ThemeEntry[]> = { colors, fonts, fontSizes };
const themeNameAliases: Record<string, string> = {
    Button: 'Buttons',
    'HTML Card': 'HTML Card',
    'Preview Color Schemes': 'Color Scheme Preview',
};

function themeEntries(widgetName: string): Array<{ type: ThemeType; entry: ThemeEntry }> {
    const name = themeNameAliases[widgetName] || widgetName;
    return (Object.keys(themeLists) as ThemeType[]).flatMap(type => themeLists[type]
        .filter(entry => entry.widget.split(', ').includes(name))
        .map(entry => ({ type, entry })));
}

function cssVariable(type: ThemeType, id: string): string {
    const normalized = id.replace(/^light\.|^dark\./, '').replace(/\./g, '-').replace(/_/g, '-');
    if (type === 'colors') return `--materialdesign-widget-theme-color-${normalized}`;
    if (type === 'fonts') return `--materialdesign-widget-theme-font-${normalized}`;
    return `--materialdesign-widget-theme-font-size-${normalized}`;
}

function themeStateId(type: ThemeType, id: string, dark = false): string {
    if (type === 'colors') return `vis2-materialdesign.0.colors.${dark ? id.replace(/^light\./, 'dark.') : id}`;
    return `vis2-materialdesign.0.${type}.${id}`;
}

export function editorDialogPalette(start: Element | null): { surface: string; text: string; secondaryText: string } {
    let current = start;
    while (current) {
        const style = window.getComputedStyle(current);
        if (style.backgroundColor && style.backgroundColor !== 'transparent' && !/rgba\([^)]*,\s*0(?:\.0+)?\)/.test(style.backgroundColor)) {
            const channels = style.backgroundColor.match(/[\d.]+/g)?.slice(0, 3).map(Number);
            const dark = !!channels && (channels[0] * 299 + channels[1] * 587 + channels[2] * 114) / 1000 < 128;
            return {
                surface: style.backgroundColor,
                text: style.color || (dark ? '#fff' : 'rgba(0, 0, 0, 0.87)'),
                secondaryText: dark ? 'rgba(255, 255, 255, 0.7)' : 'rgba(0, 0, 0, 0.6)',
            };
        }
        current = current.parentElement;
    }
    return { surface: '#fff', text: 'rgba(0, 0, 0, 0.87)', secondaryText: 'rgba(0, 0, 0, 0.6)' };
}

function UseThemeButton(props: { entries: Array<{ type: ThemeType; entry: ThemeEntry }>; data: Record<string, unknown>; onDataChange: (data: Record<string, unknown>) => void }): React.JSX.Element {
    const dialogRef = React.useRef<HTMLDialogElement>(null);
    const titleId = React.useId();
    const descriptionId = React.useId();
    const close = (): void => dialogRef.current?.close();
    const open = (event: React.MouseEvent<HTMLButtonElement>): void => {
        const dialog = dialogRef.current;
        if (!dialog || dialog.open) return;
        const palette = editorDialogPalette(event.currentTarget.parentElement);
        dialog.style.setProperty('--mdw-editor-dialog-surface', palette.surface);
        dialog.style.setProperty('--mdw-editor-dialog-text', palette.text);
        dialog.style.setProperty('--mdw-editor-dialog-secondary-text', palette.secondaryText);
        dialog.showModal();
    };
    const apply = (): void => {
        const next = { ...props.data };
        props.entries.forEach(({ type, entry }) => {
            const value = `var(${cssVariable(type, entry.id)})`;
            next[entry.desc] = value;
            Object.keys(next).filter(key => new RegExp(`^${entry.desc}\\d+$`).test(key)).forEach(key => { next[key] = value; });
        });
        props.onDataChange(next);
        close();
    };
    return <>
        <button className="mdw-editor-button mdw-editor-button--outlined" onClick={open} type="button">{VisWidget.t('useTheme')}</button>
        <dialog aria-describedby={descriptionId} aria-labelledby={titleId} className="mdw-editor-dialog" onClick={event => { if (event.target === event.currentTarget) close(); }} ref={dialogRef}>
            <div className="mdw-editor-dialog__paper">
                <h2 className="mdw-editor-dialog__title" id={titleId}>{VisWidget.t('useTheme')}</h2>
                <div className="mdw-editor-dialog__content"><p id={descriptionId}>{VisWidget.t('all colors, fonts and font sizes of the widget will be overridden - do you want to continue?')}</p></div>
                <div className="mdw-editor-dialog__actions">
                    <button className="mdw-editor-button mdw-editor-button--text" onClick={close} type="button">{VisWidget.t('cancel')}</button>
                    <button autoFocus className="mdw-editor-button mdw-editor-button--contained" onClick={apply} type="button">{VisWidget.t('ok')}</button>
                </div>
            </div>
        </dialog>
    </>;
}

function encodeThemeId(id: string): string {
    return id.replace(/_/g, '_u_').replace(/\./g, '_d_');
}

function decodeThemeId(id: string): string {
    return id.replace(/_d_/g, '.').replace(/_u_/g, '_');
}

function themeFields(widgetName: string): RxWidgetInfo['visAttrs'][number]['fields'] {
    const entries = themeEntries(widgetName);
    return [
        {
            type: 'custom',
            name: 'useTheme',
            label: 'useTheme',
            component: (_field, data, onDataChange) => <UseThemeButton entries={entries} data={data as Record<string, unknown>} onDataChange={onDataChange as (data: Record<string, unknown>) => void} />,
        },
        {
            name: '__mdwThemeDark',
            type: 'id',
            default: 'vis2-materialdesign.0.colors.darkTheme',
            hidden: () => true,
        },
        ...entries.flatMap(({ type, entry }, index) => {
            const name = `__mdwTheme_${type}_${encodeThemeId(entry.id)}_${index}`;
            return type === 'colors'
                ? [{ name, type: 'id' as const, default: themeStateId(type, entry.id), hidden: () => true }, { name: `${name}_dark`, type: 'id' as const, default: themeStateId(type, entry.id, true), hidden: () => true }]
                : [{ name, type: 'id' as const, default: themeStateId(type, entry.id), hidden: () => true }];
        }),
    ];
}

export function applyThemeVariables(data: Record<string, unknown>, values: Record<string, ioBroker.StateValue> | undefined): void {
    if (!values) return;
    const dark = data.__mdwThemeDark;
    const isDark = values[`${dark}.val`] === true || values[`${dark}.val`] === 'true';
    Object.keys(data).filter(key => key.startsWith('__mdwTheme_') && !key.endsWith('_dark')).forEach(key => {
        const stateId = data[isDark && data[`${key}_dark`] ? `${key}_dark` : key];
        const value = typeof stateId === 'string' ? values[`${stateId}.val`] : undefined;
        const parts = key.match(/^__mdwTheme_(colors|fonts|fontSizes)_(.+)_\d+$/);
        if (!parts) return;
        const variable = cssVariable(parts[1] as ThemeType, decodeThemeId(parts[2]));
        // Font sizes carry no unit in the theme state; legacy appended 'px' (setCssFontSizes). Without it a `var()` resolves to a unitless number and is ignored as a CSS font-size.
        if (value !== undefined && value !== null) document.documentElement.style.setProperty(variable, parts[1] === 'fontSizes' ? `${value}px` : String(value));
    });
}

const BaseVisWidget = window.visRxWidget as typeof VisRxWidget<BaseRxData, VisRxWidgetState>;

export class VisWidget extends BaseVisWidget {
    render(): React.JSX.Element | null {
        applyThemeVariables(this.state.rxData as unknown as Record<string, unknown>, this.state.values);
        return super.render();
    }
}

export type RenderProps = RxRenderWidgetProps;
