name: Automerge Dependabot

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: read
    steps:
      - uses: iobroker-bot-orga/action-automerge-dependabot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
